# Generated by Django 4.2.2 on 2023-08-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='atividade_foto'),
        ),
    ]
