# Generated by Django 4.2.2 on 2023-08-15 16:56

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0003_atividade_esporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='data',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
