# Generated by Django 4.2.2 on 2023-08-15 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0004_atividade_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
