# Generated by Django 4.2.2 on 2023-08-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0005_alter_atividade_data'),
    ]

    operations = [
    ]
