# Generated by Django 4.2.2 on 2023-08-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0006_auto_20230815_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
