# Generated by Django 4.2.2 on 2023-08-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_foto'),
        ('atividade', '0007_alter_atividade_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
    ]
