# Generated by Django 4.2.2 on 2023-08-19 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0008_atividade_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='esporte',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='titulo',
        ),
    ]
