# Generated by Django 4.2.2 on 2023-08-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0009_remove_atividade_cidade_remove_atividade_esporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='atividade_foto'),
        ),
    ]
