# Generated by Django 4.2.2 on 2023-08-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0010_alter_atividade_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
