# Generated by Django 4.2.2 on 2023-08-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0012_remove_atividade_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='atividade_foto'),
        ),
    ]
