# Generated by Django 4.2.2 on 2023-09-17 05:51

import atividade.models
from django.db import migrations, models
import utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0015_alter_atividade_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='foto',
            field=models.ImageField(blank=True, default='atividade_default.png', null=True, storage=utils.storages.PrivateMediaStorage(), upload_to=atividade.models.get_upload_path_atividade),
        ),
    ]
