# Generated by Django 4.2.4 on 2023-08-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('esporte', models.CharField(max_length=255)),
            ],
        ),
    ]
