# Generated by Django 4.2.2 on 2023-09-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='foto',
        ),
    ]
