# Generated by Django 4.2.2 on 2023-09-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_remove_evento_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='representa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
