# Generated by Django 4.2.2 on 2023-08-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_totaleventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='usuario_foto'),
        ),
    ]
