# Generated by Django 4.2.2 on 2023-09-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='criador',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='representa',
            field=models.CharField(blank=True, default='Nenhuma', max_length=255, null=True),
        ),
    ]
