# Generated by Django 4.2.2 on 2023-09-17 05:41

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_criador_usuario_representa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=usuario.models.get_upload_path_usuario),
        ),
    ]
