# Generated by Django 4.2.2 on 2023-09-18 00:34

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='padroes/default-user.jpg', null=True, upload_to=usuario.models.get_upload_path_usuario),
        ),
    ]
