# Generated by Django 4.2.2 on 2023-09-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='quer_criar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
